window.DAWN_DEFAULTS = {
  brand: "ZhenFrame",
  tagline: "WHERE IDEAS MEET NEW BEGINNINGS.",
  manifesto: "BRANDS / OBJECTS\nSTORIES &\nIMAGE SYSTEMS.",
  cta: "Discover my works — let's cooperate.",
  about: {
    zh: "对我来说，设计能把复杂想法变得更容易理解，化解限制，再找出满足创造欲的路径。我相信灵感藏在最平凡的地方，把这些想法变成可触摸的东西，是我一直好奇的事。",
    en: "For me, design makes complex ideas easier to understand, overcomes limits, and opens room for creativity. Inspiration lives in ordinary things — turning them into something tangible is what keeps me curious.",
  },
  contact: {
    email: "15004320356@qq.com",
    phone: "183 7396 8105",
    city: "长沙",
    cityEn: "CHANG SHA",
    wechatQr: "",
    rednoteQr: "",
    portrait: "",
  },
  resume: {
    experience: [
      { when: "2024 — Now", what: "Independent Designer · Brand & Visual" },
      { when: "2022 — 2024", what: "Studio Associate · Packaging Systems" },
    ],
    education: [{ when: "2018 — 2022", what: "BFA Visual Communication · Fiction University" }],
    cvUrl: "",
    note: "CV PDF 占位 — 后续替换真实文件",
  },
  skills: [
    { name: "MOTION", photo: "" },
    { name: "IP DESIGN", photo: "" },
    { name: "TYPOGRAPHY", photo: "" },
    { name: "BRANDING", photo: "" },
    { name: "POSTER", photo: "" },
  ],
  boardTags: [
    { en: "BRANDING", zh: "品牌设计" },
    { en: "POSTER", zh: "海报设计" },
    { en: "PACKAGING", zh: "包装设计" },
    { en: "AI VISUAL", zh: "AI视觉" },
    { en: "EDITORIAL", zh: "编辑设计" },
  ],
  updatesTitle: "OPEN TO WORK",
  updatesBlurb: "Let's create something great together. Available for full-time roles & projects.",
  updates: [
    { date: "2026.03", text: "Open to full-time & project collabs" },
    { date: "2026.01", text: "New packaging series in progress" },
    { date: "2025.11", text: "Website refresh — this board" },
  ],
  worksHero: {
    title: "ZhenFrame",
    desc: "a visual design studio exploring brands, objects, stories and image systems through graphic, packaging and AI-driven design.",
  },
  works: [
    {
      id: "laobaisha",
      year: "2026",
      name: "劳白沙",
      category: "Craft Beer",
      type: "Brand design",
      color: "#c4a574",
      side: "alt",
      desc: "虚构项目：围绕本地精酿文化的视觉识别系统，强调麦芽质感与城市夜色对比。包装、杯垫与活动主视觉占位色块，后续替换真实物料。",
      media: [
        { kind: "color", color: "#c4a574" },
        { kind: "color", color: "#8b6914" },
        { kind: "color", color: "#2d3436" },
        { kind: "color", color: "#dfe6e9" },
        { kind: "color", color: "#e17055" },
        { kind: "color", color: "#636e72" },
      ],
    },
    {
      id: "laoyouguigui",
      year: "2026",
      name: "老友桂桂",
      category: "Local Cuisine",
      type: "Brand design",
      color: "#c45c4a",
      side: "",
      desc: "虚构项目：南宁老友粉品牌叙事——酸香、街巷与「老友常来」。主视觉用红色块与书法感标题占位，详情图可替换实拍与延展物料。",
      media: [
        { kind: "color", color: "#c45c4a" },
        { kind: "color", color: "#8b2e25" },
        { kind: "color", color: "#f3eee4" },
        { kind: "color", color: "#2f3e46" },
        { kind: "color", color: "#e8b4a8" },
        { kind: "color", color: "#1a1a1a" },
      ],
    },
    {
      id: "mamba",
      year: "2025",
      name: "MAMBA",
      category: "Coffee",
      type: "Brand design",
      color: "#2d3436",
      side: "alt",
      desc: "虚构咖啡品牌：黑金调性与犀利排版。色块模拟袋装、纸杯与店头主视觉。",
      media: [
        { kind: "color", color: "#2d3436" },
        { kind: "color", color: "#fdcb6e" },
        { kind: "color", color: "#636e72" },
        { kind: "color", color: "#dfe6e9" },
        { kind: "color", color: "#111111" },
        { kind: "color", color: "#b2bec3" },
      ],
    },
    {
      id: "801coffee",
      year: "2025",
      name: "801 COFFEE",
      category: "Coffee",
      type: "Brand design",
      color: "#6c5ce7",
      side: "",
      desc: "虚构精品咖啡系列：数字「801」作为图形锚点，延展到菜单与会员卡。",
      media: [
        { kind: "color", color: "#6c5ce7" },
        { kind: "color", color: "#a29bfe" },
        { kind: "color", color: "#2d3436" },
        { kind: "color", color: "#ffeaa7" },
        { kind: "color", color: "#dfe6e9" },
        { kind: "color", color: "#0984e3" },
      ],
    },
    {
      id: "petglaussio",
      year: "2025",
      name: "PetGlaussio",
      category: "Pet Appliances",
      type: "Brand design",
      color: "#a55eea",
      side: "alt",
      desc: "虚构宠物电器品牌：柔和紫与插画感色块，模拟台历与包装展开。",
      media: [
        { kind: "color", color: "#a55eea" },
        { kind: "color", color: "#d6a2e8" },
        { kind: "color", color: "#f8f1ff" },
        { kind: "color", color: "#2d3436" },
        { kind: "color", color: "#fd79a8" },
        { kind: "color", color: "#74b9ff" },
      ],
    },
    {
      id: "sweetbox",
      year: "2024",
      name: "甜蜜盲盒",
      category: "Coffee",
      type: "Brand design",
      color: "#e84393",
      side: "",
      desc: "虚构联名盲盒包装：甜感配色与拆箱动线占位。",
      media: [
        { kind: "color", color: "#e84393" },
        { kind: "color", color: "#fd79a8" },
        { kind: "color", color: "#ffeaa7" },
        { kind: "color", color: "#2d3436" },
        { kind: "color", color: "#fab1a0" },
        { kind: "color", color: "#dfe6e9" },
      ],
    },
    {
      id: "sweetj",
      year: "2023",
      name: "SWEET J MELODY",
      category: "Bakery",
      type: "Brand design",
      color: "#d35400",
      side: "",
      desc: "虚构音乐甜品空间：旋律与烘焙交叉的形象系统。色块网格模拟主视觉拼贴与周边。",
      media: [
        { kind: "color", color: "#e67e22" },
        { kind: "color", color: "#f39c12" },
        { kind: "color", color: "#8e44ad" },
        { kind: "color", color: "#2c3e50" },
        { kind: "color", color: "#ecf0f1" },
        { kind: "color", color: "#c0392b" },
      ],
    },
    {
      id: "ckma",
      year: "2022",
      name: "CKMA",
      category: "Fresh Fruit Tea",
      type: "Brand design",
      color: "#27ae60",
      side: "alt",
      desc: "虚构鲜果茶品牌：清爽绿与果切色块，占位杯贴与海报。",
      media: [
        { kind: "color", color: "#27ae60" },
        { kind: "color", color: "#2ecc71" },
        { kind: "color", color: "#f1c40f" },
        { kind: "color", color: "#e74c3c" },
        { kind: "color", color: "#ecf0f1" },
        { kind: "color", color: "#16a085" },
      ],
    },
  ],
};
